### ISSUE TITLE
Arabic word normalization

### ISSUE THREAD

**Issue by FengYusheng** [linuxscout/ayaspell#4]
I'm finding a hunspell Arabic dictionary for word normalization. 

The README says "An Arabic morphological lexicon: grammar-ar , for the grammar-checker" is in progress. 

Are you still working in it? Or do you have a recommendation? 

Thanks

**Comment by linuxscout** [comment]
Hi,
you can find the Arabic morphology lexicon on [Arramooz Project](https://github.com/linuxscout/arramooz/).
For the grammar checker we try to work on LanguageTool, we have an alpha version  on [LT for arabic.](https://github.com/linuxscout/languagetool).
You can take a look on PyArabic library, Tashaphyme Stemmer,  Diacritizer, or Morphology analyzer on [my account](https://github.com/linuxscout/)

**Comment by FengYusheng** [comment]
Thanks you, sir

I will learn [Arramooz Project](https://github.com/linuxscout/arramooz/) during these days. If I have some questions, I will leave a message under  Arramooz Project.

You can call me Yusheng. I'm a developer from China.
