### ISSUE TITLE
How to improve Hunspell Arabic dictionary

### ISSUE THREAD

**Issue by FengYusheng** [linuxscout/ayaspell#5]
Hi Taha,

I'm Yusheng, I and my colleague are still working on hunspell for Arabic morphology analysis.

We hope hunspell can return a word's stem when we input an Arabic word. And we find an Arabic ditcionary from Firfox add-ons [Arabic spell-checking dictionary](https://addons.mozilla.org/en-US/firefox/addon/arabic-spell-checking-dictiona/).  This dictionary seems working well but it has some problems my  colleague finds:

> When I input this word إنه  into the tool ( hunspell) it return to me three results
The first one it return the exact same word I input إنه
Then it return the stem of this word which is  إن
The biggest problem and our big dilemma that it returns this one وأى which is confusing me so much , this word doesn’t have any relation to the one I input .

This add-ons mentions its dictionary is from your project **Ayaspell**. So I leave this message here.

**Can you give us some directions or suggestions about how to edit an Arabic hunspell dictionary.**

**Any tutorial link, blog or article is useful.**

Best Regards,
Yusheng

**Comment by linuxscout** [comment]
Salam,
I you still working on it?
to answer your questions.

**Comment by FengYusheng** [comment]
Hi Taha,

Sorry to reply so late. My colleague and I were trying to modify hunspell Arabic dictionary.But we don't know how to get started. I don't understand Arabic.  My colleague, he is a native speaker but he is out of office now.

I have written two word documents to record how I studied the dictionary and my problem.
Can I send them to your email for now?

*I will convert them into markdown format and copy them under this comment later. Other people on Github.com may have similar questions about Hunspell or Arabic dictionary.*

Best Regards, 
Yusheng

**Comment by linuxscout** [comment]
ok,
You are welcome

**Comment by FengYusheng** [comment]
Thanks, Taha
I sent my documents to your email just now.
I don't understand Arabic so I'm afraid my question is not very clear.
I'll try to make my comments or question more clear and concrete later.

**Comment by linuxscout** [comment]
Salam,


I have read the comments, I will explain how arabic dictionary works.

Hunspell allow to have homographs (words with same writing and different meaning) and the missing Arabic diacritics add more ambiguity.



I think that your examples have the same issue, I will explain the case of يذهبون  ( They go).


This word can be pronounced as

*  "Y a d Ha Boo na"  ( they go)  with the lemma (infinitive verb "d a ha ba", (to go).

*  "Y u d Hi Boo na " ( They make it go or  they lose it)   with the infinitive verb "A d ha ba" أذهب ( to lose, to mislay).

*  "Y u d H Hi Boo na " ( They make it gold or  they gild it)   with the infinitive verb  "d hha ba" ( to gild),   ذهّب it is like the first case without diacritics.


All this possibilities are given by Hunspell when stemming, but One is enough to prove that the word is not mistaken.



****** How verbs are represented in Arabic dictionay ***


The verb conjugation is very hard to represent with Hunspell rules, it take more efforts to build it, wa had built this rules before, where every infinitive verb has one or two entries at most, in the rule file.


Now we use an automatic verb conjugation to build the verb part of dictionary. The rules are simple, but the dictionary has many entries for the same verb.

the infinitive verb is given by "st" stem feature.


The automatic creation of verb part is developed withon arramooz project.

http://github.com/linuxscout/arramooz


Thanks
