### ISSUE TITLE
Error when running make commands

### ISSUE THREAD

**Issue by heba-alnouri** [linuxscout/ayaspell#8]
Hello, 

I'm having this issue when running this command:
`make zip`
it's giving me this error:
```
mkdir -p templates/zip
The syntax of the command is incorrect.
make: *** [zip] Error 1
```
then I tried another command:
`make libreoffice `
also it gave me an error:
```
#copy dic and aff files to OpenOffice/LibreOffice package
process_begin: CreateProcess(NULL, #copy dic and aff files to OpenOffice/LibreOffice package, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [libreoffice] Error 2
```
Could you tell me what is the issue?

**Comment by linuxscout** [comment]
السلام عليكم،
هل شغلت هذا السكريبت على وندوز؟
هو مصمم للاشتغال على لينكس

مع تحياتي

**Comment by heba-alnouri** [comment]
ااه شغلته على وندوز.
يعطيك العافية
